# Generated by Django 4.1 on 2022-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='Admin', max_length=30, verbose_name='Name')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='User ID in Telegram')),
                ('admin', models.BooleanField(default=False, verbose_name='If user admin true/else false')),
                ('admin_leverage', models.PositiveIntegerField(default=10, verbose_name='Admin default leverage')),
                ('trailing', models.FloatField(default=0.5, verbose_name='TRAILING_STOP_MARKET Percent')),
                ('balance', models.FloatField(default=8.0, verbose_name='Balance allocated for order')),
                ('api_key', models.CharField(blank=True, max_length=265, verbose_name='api_key')),
                ('api_secret', models.CharField(blank=True, max_length=265, verbose_name='api_secret')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True, verbose_name='ID ордера')),
                ('origQty', models.FloatField(verbose_name='Объем ордера')),
                ('price', models.FloatField(verbose_name='Цена ордера')),
                ('avgPrice', models.FloatField(verbose_name='avgPrice Цена ордера')),
                ('closePosition', models.BooleanField(blank=True, verbose_name='closePosition Order')),
                ('cumQuote', models.CharField(max_length=15, verbose_name='cumQuote')),
                ('executedQty', models.CharField(max_length=15, verbose_name='executedQty')),
                ('origType', models.CharField(max_length=15, verbose_name='origType')),
                ('positionSide', models.CharField(max_length=15, verbose_name='positionSide')),
                ('priceProtect', models.BooleanField(blank=True, verbose_name='priceProtect Order')),
                ('reduceOnly', models.BooleanField(blank=True, verbose_name='reduceOnly Order')),
                ('side', models.CharField(max_length=15, verbose_name='Покупка/Продажа')),
                ('status', models.CharField(max_length=35, verbose_name='Статус ордера')),
                ('symbol', models.CharField(max_length=25, verbose_name='Валютная пара')),
                ('types', models.CharField(max_length=25, verbose_name='Тип ордера')),
                ('stop_price', models.FloatField(verbose_name='Стоп цена')),
                ('status_second', models.BooleanField(default=False, verbose_name='Status Order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trader', models.CharField(max_length=25, verbose_name='NAME Trader')),
                ('symbol', models.CharField(max_length=15, verbose_name='Symbol')),
                ('side', models.CharField(default='none', max_length=55, verbose_name='SIDE')),
                ('size', models.CharField(max_length=55, verbose_name='Size')),
                ('entry_price', models.CharField(max_length=55, verbose_name='Entry Price')),
                ('mark_price', models.CharField(max_length=55, verbose_name='Mark Price')),
                ('pnl', models.CharField(max_length=55, verbose_name='PNL (ROE %)')),
                ('date', models.CharField(max_length=55, verbose_name='TIME')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('link', models.CharField(max_length=255, verbose_name='LINK TO PROFILE')),
            ],
        ),
    ]
