# Generated by Django 4.0.5 on 2022-10-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='User name')),
                ('api_key', models.CharField(max_length=350, verbose_name='Api Key')),
                ('api_secret', models.CharField(max_length=350, verbose_name='Api Secret')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AlterField(
            model_name='admin',
            name='balance',
            field=models.CharField(choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], default='25', max_length=5, verbose_name='Balance percent allocated for order'),
        ),
    ]
