# Generated by Django 4.1.2 on 2022-10-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_users_delete_orders_alter_admin_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='trailing',
        ),
        migrations.AddField(
            model_name='users',
            name='subs_active',
            field=models.BooleanField(default=False, verbose_name='Whether copying to this account is active'),
        ),
    ]
