# Generated by Django 4.1.2 on 2022-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_remove_admin_trailing_users_subs_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='mark_price',
        ),
        migrations.AddField(
            model_name='signal',
            name='closing_price',
            field=models.CharField(default='null', max_length=25, verbose_name='Closing Price'),
        ),
        migrations.AddField(
            model_name='signal',
            name='leverage',
            field=models.IntegerField(default=10, verbose_name='Leverage'),
        ),
        migrations.AddField(
            model_name='signal',
            name='position',
            field=models.CharField(default='null', max_length=10, verbose_name='Open/Close'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='date',
            field=models.CharField(default='null', max_length=55, verbose_name='TIME'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='pnl',
            field=models.CharField(default='null', max_length=55, verbose_name='PNL (ROE %)'),
        ),
    ]
