# Generated by Django 4.1.2 on 2022-10-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_remove_signal_mark_price_signal_closing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='entry_price',
            field=models.FloatField(max_length=55, verbose_name='Entry Price'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='size',
            field=models.FloatField(max_length=55, verbose_name='Size'),
        ),
    ]
