# Generated by Django 4.1.2 on 2022-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_alter_signal_closing_price_alter_signal_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='date',
            field=models.CharField(default='none', max_length=55, verbose_name='TIME'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='pnl',
            field=models.CharField(default='none', max_length=55, verbose_name='PNL (ROE %)'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='position',
            field=models.CharField(default='none', max_length=10, verbose_name='Open/Close'),
        ),
    ]
