# Generated by Django 4.1.3 on 2022-11-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0008_remove_signal_closing_price_remove_signal_leverage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25, verbose_name='Symbol')),
                ('price', models.FloatField(verbose_name='Price order')),
                ('status_second', models.BooleanField(default=True, verbose_name='Status Order')),
                ('order_id', models.CharField(max_length=35, verbose_name='Order ID')),
                ('side', models.CharField(max_length=35, verbose_name='Order side (long/short)')),
                ('size', models.FloatField(default=0, verbose_name='Size order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='signal',
            name='update',
            field=models.CharField(default=1, max_length=86, verbose_name='Update time order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='balance',
            field=models.CharField(default=10, max_length=5, verbose_name='Balance allocated for order'),
        ),
    ]
