# Generated by Django 4.1.3 on 2022-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0009_orders_delete_users_signal_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='bot_token',
            field=models.CharField(default=12, max_length=255, verbose_name='Token bot telegram'),
            preserve_default=False,
        ),
    ]
