# Generated by Django 4.1.3 on 2022-11-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_admin_bot_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='update',
            new_name='updates',
        ),
    ]
