# Generated by Django 4.1.3 on 2022-11-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0011_rename_update_signal_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='updates',
            new_name='upd',
        ),
    ]
